### PR TITLE
fix(types): add registryUrl and agent options

### PR DESCRIPTION
**Pull request by Luchanso**
Add some options

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is not a fix. Those options are not officially exposed.

---

From the registryUrl option docs:

> This option is only intended for internal tools. You should not use this option in reusable packages. Prefer just using .npmrc whenever possible.

What is your use-case for needing this? The more options I expose, the harder it is to use this module.

**Comment by Luchanso** [comment]
I need use this for private packages from private registry. Don't worry about it, I forked and publish self package for this.

**Comment by Luchanso** [comment]
You can close this PR

**Comment by Luchanso** [comment]
And "fix" about conventional commits, not about fix 🙂 
https://www.conventionalcommits.org/en/v1.0.0/

**Pull request closed without merging**
